import Head from 'next/head'
import Hero from '../components/Hero';
import Apartments from '../components/Apartments';
import { GraphQLClient , gql } from 'graphql-request'

export const getStaticProps = async () => {

  const url = "https://api-eu-central-1.graphcms.com/v2/cl45ontud0oz701yvf32n60z2/master";
  const client = new GraphQLClient(url, {
      headers: {
      authorization : 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImdjbXMtbWFpbi1wcm9kdWN0aW9uIn0.eyJ2ZXJzaW9uIjozLCJpYXQiOjE2NTQ3MDU5MDUsImF1ZCI6WyJodHRwczovL2FwaS1ldS1jZW50cmFsLTEuZ3JhcGhjbXMuY29tL3YyL2NsNDVvbnR1ZDBvejcwMXl2ZjMybjYwejIvbWFzdGVyIiwiaHR0cHM6Ly9tYW5hZ2VtZW50LW5leHQuZ3JhcGhjbXMuY29tIl0sImlzcyI6Imh0dHBzOi8vbWFuYWdlbWVudC5ncmFwaGNtcy5jb20vIiwic3ViIjoiZDY2ZTU0NWYtMDlmNi00ZDcwLTk1ZWItMzU0OTQ3YWEyZDliIiwianRpIjoiY2w0NXQ2ODR0MHpoYTAxeXdhYjhvZ2V3MSJ9.HOGlLmH7bbOFR2NZXw4oIJYRRUzK0hd6AIuz4fZMMLApqziH8YkHoOgSE8eqVvkZpixGUj-7KDYDN-AyysqPOR2xitzu6V70igEEt3d7ukaDxgMhe2aYEM0swYsrMcwiJPDjbVdF1FMtgPG9vz3HwVnaL48uW8wmgWJIZkNq8WjiiJSARYsdTc0Ab-N-9CU-tAVdiS23xlT8RfVKC704L4S5Ity5hKSIvS5ivNdUZOm5EnL-8mz7MzTJorUjZ9pFyi8pOYoywngWMVvxlk95DNUKrsb8t1xzPSgLJws273DLiSH9pitfPj73UdccFtDFLnlkzNjbmDntM6EOb5mXJeeFoJdiyi4JzM_lGk-EiDOTCFxcaPqPsOc-ZkI9VflOmRNuZ4MuFc3ITkYgJ8D67L7NURHa6bB7F5cv9ymJQP1xeNN9Ws_PHorcco563YAyWI7vxhurFWvPQU_vASmy36WOxN58H9m6oowezuLsw3LQxlQjvZfuECoSWyxEaPER6Kp_KrRMBNvdUm4Daws_iLosbtix8C8w0_mShssmJ-WRfXXiQB9e42j1NqvwHbxotaA_L_N0G18XspXgf1mwG_t0hDH6kjYfFTvj6EAYHrCJDMZpSmf46NicHYWIJajWS80Y2ltWSM7kEm8GLu_V8RwDnJSDjLdND-3_VVYDf08',
  } })

  const query = gql`
      query{
          apartments {
            title,
            address,
            price,
            numberOfRooms,
            numberOfToalets,
            numberOfParkingPlace,
            apartmentDescription,
            propertySize,
            numberOfPersons,
            city,
            owner,
            apartmentVideo {
              url
            },
            phone, 
            slug,
            apartmentImage {
              url
            }
          }
        }
  `

  const apartmentData = await client.request(query);
  const data = apartmentData.apartments;

  return {
      props: {
          data
      }
  }

}

export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>Rezervišite Apartman - Nemanja Radivojevic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero
        title="Pronađite idealan smeštaj za Vaš sledeći odmor."
        description="Pretražite veliki izbor apartmana za Vaš savršen odmor."
        buttonURL="/" buttonText="Kontakt"
        imageURL="/01.jpg"
      />
      <Apartments apartmentsData={data} />

    </div>
  )
}
